import { Link } from "@mui/material";
import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useRecoilValue } from "recoil";
import styles from "../../styles/Home.module.css";
import { authState } from "../store/AuthState";

type Response = {
  message: string;
};

const Home: NextPage = () => {
  const [message, setMessage] = useState("");
  const auth = useRecoilValue(authState);
  useEffect(() => {
    const url = "http://localhost:8000/api/hello";
    const f = async () => {
      const res = await axios.get(url, {
        headers: { Authorization: "Bearer " + auth?.accessToken },
      });
      console.log(res);
      setMessage(res.data.message);
    };
    f();
  }, [auth?.accessToken]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h3>{message}</h3>

        <div>
          <Link href="auth/signin" variant="body2">
            サインイン
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
